export const membersData = [
    {
        email: "isabella@test.com",
        username: 'isabellatest',
        gender: "female",
        dateOfBirth: "1996-07-22",
        name: "Isabella T.",
        created: "2023-06-24",
        lastActive: "2024-06-10",
        description: "Adventurous traveler with a passion for photography. Enjoys hiking, beach sunsets, and trying new cuisines. Looking for someone who shares a love for the outdoors and spontaneous weekend getaways.",
        city: "Madrid",
        country: "Spain",
        image: "https://img.freepik.com/free-photo/low-angle-young-woman-nature_23-2148523896.jpg"
    },
    {
        email: "Anna@test.com",
        username: 'annatest',
        gender: "female",
        dateOfBirth: "1995-10-12",
        name: "Anna T.",
        created: "2023-12-09",
        lastActive: "2024-05-06",
        description: "Dog lover and coffee enthusiast. Enjoys cozy nights with a good book or movie. Works in marketing and values meaningful conversations. Seeking a kind-hearted partner who appreciates the little things in life.",
        city: "Kishinev",
        country: "Moldova",
        image: "https://img.freepik.com/free-photo/young-woman-model-leather-jacket-outside-street_1303-20492.jpg"
    },
    {
        email: "cassia@test.com",
        username: 'cassiatest',
        gender: "female",
        dateOfBirth: "1999-01-24",
        name: "Cassia T.",
        created: "2023-08-10",
        lastActive: "2024-05-12",
        description: "Fitness instructor who loves staying active. Enjoys yoga, running, and exploring new fitness trends. Also a foodie at heart, always on the hunt for the best local eateries. Looking for an active, health-conscious partner.",
        city: "Drama",
        country: "Greece",
        image: "https://img.freepik.com/free-photo/woman-home_144627-40918.jpg"
    },
    {
        email: "ruthie@test.com",
        username: 'ruthietest',
        gender: "female",
        dateOfBirth: "1996-01-12",
        name: "Ruthie T.",
        created: "2019-04-30",
        lastActive: "2024-06-11",
        description: "Creative spirit with a love for art and music. Enjoys painting, attending live concerts, and exploring museums. Looking for someone who shares an appreciation for creativity and artistic endeavors.",
        city: "Dublin",
        country: "Ireland",
        image: "https://img.freepik.com/free-photo/elegant-woman-waiting-restaurant_1140-520.jpg"
    },
    {
        email: "andrei@test.com",
        username: 'andreitest',
        gender: "male",
        dateOfBirth: "1997-04-09",
        name: "Andrei T.",
        created: "2023-04-05",
        lastActive: "2024-06-06",
        description: "Software engineer with a passion for technology and innovation. Enjoys gaming, coding, and sci-fi movies. Looking for a like-minded partner who appreciates geek culture and tech talk.",
        city: "Cluj-Napoca",
        country: "Romania",
        image: "https://img.freepik.com/free-photo/portrait-handsome-confident-stylish-hipster-lambersexual-model-with-curly-hairstyle-sexy-man-dressed-jeans-jacket-fashion-male-isolated-blue-wall-studio-touching-his-chin_158538-26550.jpg"
    },
    {
        email: "elin@test.com",
        username: 'elintest',
        gender: "male",
        dateOfBirth: "1990-03-23",
        name: "Elin T.",
        created: "2023-03-14",
        lastActive: "2024-05-17",
        description: "Fitness enthusiast and personal trainer. Enjoys weightlifting, sports, and meal prepping. Values a healthy lifestyle and is looking for someone who shares a commitment to fitness and well-being.",
        city: "Plovdiv",
        country: "Bulgaria",
        image: "https://img.freepik.com/free-photo/young-male-traveler-posing-smiling_23-2149118742.jpg"
    },
    {
        email: "Yanko@test.com",
        username: 'yankotest',
        gender: "male",
        dateOfBirth: "1992-12-01",
        name: "Yanko T.",
        created: "2023-01-28",
        lastActive: "2024-06-07",
        description: "Outdoorsman who loves fishing, camping, and hiking. Enjoys quiet evenings by the campfire and star gazing. Seeks a partner who enjoys nature and isn't afraid of a little adventure.",
        city: "Varna",
        country: "Bulgaria",
        image: "https://img.freepik.com/free-photo/young-handsome-redhead-model-man-flannel-shirt-gray-background_613910-19116.jpg"
    },
    {
        email: "petar@test.com",
        username: 'petartest',
        gender: "male",
        dateOfBirth: "1988-03-20",
        name: "Petar T.",
        created: "2023-02-25",
        lastActive: "2024-06-11",
        description: "Chef and food lover. Enjoys experimenting in the kitchen and hosting dinner parties. Passionate about trying new recipes and ingredients. Looking for someone who loves good food and great conversation.",
        city: "Yambol",
        country: "Bulgaria",
        image: "https://img.freepik.com/free-photo/young-handsome-man-posing_144627-28076.jpg"
    }
]