name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Start database services
        run: docker compose up -d

      - name: Timeout 30 seconds
        run: sleep 30

      - name: Generate prisma
        run: npx prisma generate

      - name: Timeout 30 seconds
        run: sleep 30

      - name: Push DB
        run: npx prisma db push

      - name: Timeout 30 seconds
        run: sleep 30

      - name: Seed DB
        run: npx prisma db seed
      
      - name: Timeout 30 seconds
        run: sleep 30

      - name: Build React app
        run: npm run build
