name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Start database services (using Docker Compose)
        run: docker-compose up -d db

      - name: Timeout 5 minutes
        run: sleep 300

      - name: Run database migrations (using Docker Compose)
        run: docker-compose exec db prisma migrate deploy

      - name: Build React app
        run: npm run build
